[[redirects]]
  from = "https://drug-info.netlify.app/main"
  to = "https://drug-info.netlify.app/"
  status = 200


[[redirects]]
  from = "/1471000/*"
  to = "http://apis.data.go.kr/:splat"
  status = 200
  force = true